[build]
  base = "frontend"
  publish = "frontend/build"
  command = "npm run build"

[build.environment]
  REACT_APP_USE_MOCK_API = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
