[build]
  base = "hackathon-frontend"
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_USE_MOCK_API = "false"
  REACT_APP_API_URL = "https://hackathon-portal-project-8737.onrender.com"
  EXTEND_ESLINT = "true"
  DISABLE_ESLINT_PLUGIN = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
